
project_id = "dfaunbusectzqdlkyche"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
external_url = "http://localhost:54320"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_email_change_enabled = true
enable_signup = true

[functions]
verify_jwt = true

[db]
port = 54322
shadow_port = 54323
major_version = 15
