// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfaunbusectzqdlkyche.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYXVuYnVzZWN0enFkbGt5Y2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzU1MTgsImV4cCI6MjA2MDYxMTUxOH0.teK6V4_6SXo3GnN-VZDJZxO3Eepi8rrmY4kF4FVuGH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);